### ISSUE TITLE
Mime type not specified?

### ISSUE THREAD

**Issue by apellerite** [elegantmonkeys/node-slack-upload#10]
I tried using the example code with my own file, and I keep getting the error `markdown_conversion_failed_because_of_content or mime type is not specified...`.
I've tried including a contentType field in the parameters, but that doesn't seem to help. Is there a simple fix to this?

**Comment by idoshamun** [comment]
Actually I haven't use this package for a while now, try digging into Slack API help center. Maybe you can find your answer over there

**Comment by idoshamun** [comment]
@apellerite have you find the answer?

**Comment by kubark42** [comment]
Same problem here, but alas I have no real understanding of where to start digging to solve the problem.

**Comment by kubark42** [comment]
@idoshamun, @apellerite, the answer is just to change the file type to be appropriate. Check out https://api.slack.com/types/file#file_types for more details. I was able to upload an image by using

`filetype: 'auto'` instead of `filetype: 'post'` in the example. Magic!

**Comment by idoshamun** [comment]
Thanks for answering the issue!
