### ISSUE TITLE
Is there any way to use this with a Buffer or pipe?

### ISSUE THREAD

**Issue by shawngiese** [elegantmonkeys/node-slack-upload#6]
So, if I wanted to download a file from one location (without writing it to the filesystem) and then uploading it to slack.

**Comment by idoshamun** [comment]
You can just provide your stream as a value for the `file` property. Let me
know if works.

P.S sorry for the late response, I'm in a vacation

**Comment by idoshamun** [comment]
Have you managed to resolve this?

**Comment by idoshamun** [comment]
Closing this issue due to long time without updates
