### ISSUE TITLE
Problem with callback 'data'

### ISSUE THREAD

**Issue by dino993** [elegantmonkeys/node-slack-upload#8]
code:
```
this.slackUploader.uploadFile({
            file: fs.createReadStream(__dirname.split("tools")[0] + "output/screenshots/" + screenName + '.png'),
            filetype: 'png',
            title: screenName,
            initialComment: this.js_functions.getFullDate(),
            channels: '#myChannel'
        }, function (err, data) {
            if (err) {
                console.error(err.message);
            } else {
                console.log('Uploaded file details: ', data.file.url_private);
            }
        })
```

problem description:
'err' works correct, for example, in case of wrong path to file I get err.message. But when I upload file to slack channel, I get 'data' is not defined. It happens because there is short period of time until file is uploaded.  It is true, I can't get data.file.url_private of file that is not uploaded yet. How can I wait this event and get   'data.file.url_private' only after it.

**Comment by idoshamun** [comment]
Actually `data` should be defined when `callback` is called as of version 1.2.0  (#7).
What version do you use?

**Comment by dino993** [comment]
I have got reason. There are two options how I run my mocha tests.

1) I run each test separately in IDE. In this case I can't get **data.file.url_private** in log because my test completes earlier then file is uploaded to slack. (test log is no available)

2) I run all tests in gitlab. In this case I get in log **data.file.url_private** but it happens in log of next test as new test have already started.

I hope it was explained clearly

**Comment by idoshamun** [comment]
It sounds like you are not creating an async test in mocha but a sync one, it doesn't sound like an issue that belongs here. But please share your entire test case and I'll try to help

**Comment by dino993** [comment]
My test case:

```
var target = require('../app/application'),
    test = require('selenium-webdriver/testing'),
    assert = require('assert');

var c_o_param = require('../parameters/create_order_parameters');

test.describe('!!!!!!!!!02_Тест авторизации с помощью кнопки "Войти"!!!!!!!!!', function() {
    var app;
    var passwordToSystem;

    test.before(function*() {
        app = new target.Application();
        passwordToSystem = yield app.getEmailPasswordFromFile();
    });

    test.it('Тест авторизации с помощью кнопки "Войти"', function() {
        app.goToAuthorizationPageFromLandinPageEnterButton()
            .doAuthorization(
                passwordToSystem,
                c_o_param.inputForCreateOrderStageOne.firstName,
                c_o_param.inputForCreateOrderStageOne.lastName
            )
            .doLogout();
    });

    test.after(function() {
        var testFileName = __filename.split("/tests/")[1];
        app.onFailActivities(testFileName).quit();
    });
});
```

I am sending screen in function `app.onFailActivities(testFileName)` by calling inside function uploadScreen(screenName)

```
uploadScreen(screenName) {

       this.slackUploader.uploadFile({
            file: fs.createReadStream(__dirname.split("tools")[0] + param.app_parameters.pathToFailedScreen + screenName + '.png'),
            filetype: 'png',
            title: screenName,
            initialComment: this.js_functions.getFullDate(),
            channels: '#bg2_build_output'
        }, function (err, data) {
            if (err) {
                console.error(err.message);
            } else {
                console.log('Uploaded file details: ', data.file.url_private);
            }
        })
    }
```

**Comment by idoshamun** [comment]
Your `test.after` function has async operation inside it `app.onFailActivities` but you use the sync form. You should use the `done` callback of `after` and call it when you done all the async processing.
Otherwise it will stop running as soon as it runs all functions without waiting for response

**Comment by dino993** [comment]
Thanks, I got it. With done, test suite doesn't stop and wait until file is uploaded and return response. But, I guess there is smth wrong with my async functions as test suite doesn't stop until mocha timeout (60 sec). Smth freezes and I don't want what exactly

**Comment by idoshamun** [comment]
Maybe you are not calling the `done` callback when you finish running your
test

**Comment by idoshamun** [comment]
Anyway It feels like it is no longer an issue for this module.
If you want I would be happy to assist via email but I am closing this one
