### ISSUE TITLE
error on large files

### ISSUE THREAD

**Issue by McSlurryHole** [elegantmonkeys/node-slack-upload#9]
I get a `markdown_conversion_failed_because_of_read_failed` error when tying to upload a 12k line json file, is it timing out on upload or something?, replacing the file with a smaller one works fine.

**Comment by idoshamun** [comment]
I think you should advise Slack support, it seems that it is an issue with their API

**Comment by kewitz** [comment]
I'm also having this problem.
Could someone explain what are the real limitations we have in the `files.upload` endpoint?

**Comment by idoshamun** [comment]
@McSlurryHole have you find the answer?

**Comment by McSlurryHole** [comment]
@idoshamun It's been 8 months so I don't quite remember but I did contact slack and it was a problem with their API. from memory there was a certain flag I had to set or something, you can probably close this issue.

**Comment by idoshamun** [comment]
thanks for the quick answer :)
